development:
  host: localhost
  database: mvp_development

test:
  host: localhost
  database: mvp_test


# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOLAB_URI'] %>
  #host: localhost
  #database: mvp_production
 # host: <%= ENV['MONGOID_HOST'] %>
  #port: <%= ENV['MONGOID_PORT'] %>
  #username: <%= ENV['MONGOID_USERNAME'] %>
  #password: <%= ENV['MONGOID_PASSWORD'] %>
  #database: <%= ENV['MONGOID_DATABASE'] %>
#  uri: <%= ENV['MONGOHQ_URL'] %>


  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
